#!/bin/bash
# Deploy script for Withlinux
# Copyright (C) 2016 Zhou Mo <cdluminate AT gmail DOT com>
# MIT License
set -e
. lang/lumin_log.sh

warn "---------------------------------------------------------------"
warn "This script just installs/restores personal working environment"
warn "---------------------------------------------------------------"

error 'WIP: this is a work in progress'
