#!/bin/sh
# my pandoc * -> pdf convertion helper
# where * can be {markdown, rst, ...}
set -e

LATEXOPT="-V mainfont=times -V geometry=margin=1in"
TOC="--toc -V toccolor=magenta"
#LATEXOPT="$LATEXOPT $TOC"

die () {
	echo $1
	exit 1
}
pre () {
	printf "=> Processing ... "
}
post () {
	printf "[Done]\n"
}

if test "$#" -eq 1; then
	stat $1 >/dev/null || die 'stat failed'
	pre
	pandoc $LATEXOPT -o $1.pdf $1
	post
elif test "$#" -gt 1; then
	filename=$1
	stat $filename >/dev/null || die 'stat failed'
	shift;
	pre
	pandoc $LATEXOPT -o $filename.pdf $filename $@
	post
elif test "$#" -lt 1; then
	die 'No source file specified.'
fi
