#!/bin/sh
set -e
. ../lang/lumin_log.sh

# packages
packages="
ack
axel
bbswitch-dkms
build-essential
busybox-static
command-not-found
cryptsetup
debhelper
debmake
debmirror
devscripts
docker.io
dstat
eatmydata
ecryptfs-utils
fail2ban
fcitx
fcitx-googlepinyin
ffmpeg
filezilla
fish
gdb
git
git-buildpackage
gitg
gpm
gsmartcontrol
guake
hdf5-tools
htop
i3
ipython3
julia
less
libblas-dev
libgoogle-glog-dev
libhdf5-dev
libopenblas-dev
lm-sensors
lshw
ltrace
luajit
lyx
mawk
octave
openconnect
pppoeconf
progress
python3-ipdb
qemu
quilt
rfkill
rsync
rustc
sed
smartmontools
sqlite3
sshfs
strace
subversion
sudo
taskwarrior
texlive-full
tpp
ttf-ubuntu-font-family
ubuntu-dev-tools
unar
vim
virtualbox
w3m
wesnoth
wine32-development
zfsnap
zfsutils-linux
"

# start scanning
for pkg in $packages; do
  if (dpkg -s $pkg 1>/dev/null 2>&1); then
    if (dpkg -s $pkg | grep ^Status | grep 'install ok installed' 1>/dev/null); then
      info "scan pkg: $pkg ... install ok"
    else
      warn "scan pkg: $pkg ... missing"
    fi
  else
    error "scan pkg: $pkg ... missing or invalid"
  fi
done
