# lumin's xinitrc
# referece: https://wiki.archlinux.org/index.php/I3
xautolock -time 1 -locker "i3lock" &
xset r rate 190 60
xset -b
exec i3
#feh --bg-scale /usr/share/backgrounds/gnome/adwaita-day.jpg
xsetroot -gray
#xsetroot -solid "#333333"
#exec lxqt-session
#exec dbus-launch gnome-session
#exec dbus-launch gnome-session-classic
