# lumin's xinitrc
# referece: arch wiki
xset r rate 190 60
xset -b
exec i3
#feh --bg-scale /usr/share/backgrounds/gnome/adwaita-day.jpg
xsetroot -gray
#xsetroot -solid "#333333"
#exec lxqt-session
#exec dbus-launch gnome-session
#exec dbus-launch gnome-session-classic
