#!/bin/sh
set -e +x
# requires package
#   zfsutils-linux
#   zfsnap

# My ZPOOL and ZFS Wrapper
Usage () {
  cat << EOF
$0 <shortcut> [pool]
Shortcut:
  -h            show help message
  ls            list zpool and zfs
  lss           list all snapshots
  la            list all zpool and zfs
  st            show zpool status
  check <pool>  scrub a pool
  snap  <pool>  rotate snapshots for a pool
  find          show zfs currently in use
  hist  <pool>  dump history of a pool
  io            verbose iostat with interval 1
  all           show mounted zfs, list all zpool and zfs
  -v            show zfs version
EOF
}

mkhr () {
  local char
  if test -z "$1"; then
    char='='
  else
    char=$1
  fi
  sudo true
  /bin/echo -en "\x1b[1;33m"
  for i in $(seq 0 78); do
    printf "$char"
  done
  /bin/echo -e "\x1b[m"
}

if test -z "$1"; then
  Usage; exit
fi

case "$1" in
-h)
  Usage; exit ;;
ls)
  mkhr; sudo zpool list; mkhr -; sudo zfs list; mkhr; exit ;;
lss)
  sudo zfs list -tsnap; exit ;;
la)
  mkhr; sudo zpool list -v; mkhr; sudo zfs list -tall; mkhr; exit ;;
st)
  sudo zpool status -v;;
check)
  sudo zpool scrub $2 ;;
snap)
  sudo zfSnap -a 32d -r $2 ;;
autosnap)
  sudo zfSnap -a 32d -r $2; sudo zfSnap -d ;;
find)
  findmnt -t zfs ;;
hist)
  sudo zpool history $2 ;;
io)
  sudo zpool iostat -v 1 ;;
all)
  $0 find; $0 la ;;
-v)
  sudo zpool upgrade -v ;;
*)
  Usage; exit ;;
esac
