#!/bin/sh
# HTCondor Wrapper for convenience and preference
# Copyright (C) 2016 Zhou Mo <cdluminate AT gmail DOT com>
# MIT License
set -e

condor_detect () {
if condor_status 2>&1 1>/dev/null; then
  true
else
  echo "PLEASE START HTCondor Service!"
  exit 1
fi
}

split_line () {
printf "////////////////////////////////////////////////////////////////\n"
}

Usage () {
echo "Usage: $1 <ACT> <args> => condor_ACT <args>"
cat << EOF
My Alias:
  ls -> q,  push -> qsub,  commit -> submit, st -> stauts
EOF
}

howisitgoing () {
  condor_who
  split_line
  condor_status
  split_line
  condor_q
}

condor_detect

if [ -z "$1" ]; then
  howisitgoing
  exit 0
fi

if [ -z "`which condor_$1`" ]; then
  case "$1" in
  'ls') # alias 'ls' -> 'q'
    shift; condor_q $@
    ;;
  'push') # alias 'push' -> 'qsub'
    shift; condor_qsub $@
    ;;
  'st') # alias 'st' -> status
    shift; condor_status $@
    ;;
  'hi') # alias 'hi' -> history
    shift; condor_history $@
    ;;
  '-h') # dump Usage
    Usage
    ;;
  *)
    echo 'Unkown command'
    exit 1
    ;;
  esac
else
  act=$1
  shift
  condor_$act $@
fi
