main:
	f95 hello.f95 -o hello.elf -Wall
	f95 types.f95 -o types.elf -Wall
	f95 operators.f95 -o operators.elf -Wall
	f95 control.f95 -o control.elf -Wall
	f95 arrays.f95 -o arrays.elf -Wall
clean:
	-$(RM) *.elf
	
