#!/bin/sh
set -e

BOX=__T430s__

if test -z "$1"; then
	gcc dwmstatus.c -lX11 -O2 -o ~/bin/dwmstatus -pedantic -D$BOX
else
	echo "=> MODULES TEST"
	gcc dwmstatus.c -lX11 -O2 -o ./dwmstatus.test -pedantic -D$BOX -DTEST
	./dwmstatus.test
	echo "=> NORMAL TEST"
	gcc dwmstatus.c -lX11 -O2 -o ./dwmstatus.test -pedantic -D$BOX
	./dwmstatus.test
	echo "=> NOSLEEP TEST"
	./dwmstatus.test nosleep
	rm dwmstatus.test || true
fi
